### ISSUE TITLE
"Simon Game Challenge" - Not used in the case of Mobile Phones ,Tablet

### ISSUE THREAD

**Issue by arsha32** [sdkdeepa/Udemy-web-bootcamp#7]
"I am new to web development . I found a solution for it .I want to solve it under your guidance"

**Comment by vishalkhyatriya12** [comment]
![Screenshot 2023-10-24 091740](https://github.com/sdkdeepa/Udemy-web-bootcamp/assets/136780599/64a1a687-d921-475f-a26e-7ddd2271e9b1)
Its working cool on my desktop y do you want this game on Mobile or tablet

**Comment by sdkdeepa** [comment]
great!

**Comment by vishalkhyatriya12** [comment]
Yeeaahh!! Your profile & skills that you is really awesome mam!!
Congrats and keep going mam!
#googlewebexpert✅

**Comment by vishalkhyatriya12** [comment]
Skills that you have**...
What one suggestion you would give to final year student to start his/her career at google

**Comment by sdkdeepa** [comment]
> Skills that you have**... What one suggestion you would give to final year student to start his/her career at google

Participate in the code challenge that they have. Do hackathons and if you have time contribute to open source projects!
